// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/addon/addLocalResourcepack': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addon/addLocalResourcepack.post').default>>>>
    }
    '/api/addon/addRemoteResourcepack': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addon/addRemoteResourcepack.post').default>>>>
    }
    '/api/addon/getResourcepack': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addon/getResourcepack.post').default>>>>
    }
    '/api/addon/resourcepack/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addon/resourcepack/[...]').default>>>>
    }
    '/api/addon/setResourcepack': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addon/setResourcepack.post').default>>>>
    }
    '/api/auth/hasAdmin': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/hasAdmin.get').default>>>>
    }
    '/api/auth/hasPermission': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/hasPermission.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/registerAdmin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/registerAdmin.post').default>>>>
    }
    '/api/auth/verifyToken': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verifyToken.post').default>>>>
    }
    '/api/daemon/addDaemon': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daemon/addDaemon.post').default>>>>
    }
    '/api/daemon/getDaemonList': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daemon/getDaemonList.post').default>>>>
    }
    '/api/daemon/removeDaemon': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daemon/removeDaemon.post').default>>>>
    }
    '/api/downloadFile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloadFile.post').default>>>>
    }
    '/api/eula/agreedEula': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eula/agreedEula.get').default>>>>
    }
    '/api/eula/agreeEula': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eula/agreeEula.get').default>>>>
    }
    '/api/getMeta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getMeta.get').default>>>>
    }
    '/api/update/check': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update/check.post').default>>>>
    }
    '/api/update/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update/update.post').default>>>>
    }
    '/api/uploadFile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploadFile.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.4_eslint@9.11.1_jiti@2.1.2__ioredis@5.4.1__6cnuumjzuxbfmcavuhqogggg4a/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}