files:
  - source: /packages/commons/src/assets/i18n/zh-CN.json
    translation: /packages/commons/src/assets/i18n/%locale%.json
  - source: /apps/web/assets/i18n/zh-CN.json
    translation: /apps/web/assets/i18n/%locale%.json
  - source: /apps/app/src/assets/i18n/zh-CN.json
    translation: /apps/app/src/assets/i18n/%locale%.json
