import { createRouter, createWebHistory } from "vue-router";

export default createRouter({
  history: createWebHistory(),
  routes: [
    { path: "/", redirect: "/components/buttons" },
    { path: "/components/buttons", component: () => import("./pages/ButtonsPage.vue") },
    { path: "/components/input", component: () => import("./pages/InputPage.vue") },
    { path: "/components/select", component: () => import("./pages/SelectPage.vue") },
    { path: "/components/slider", component: () => import("./pages/SliderPage.vue") },
    { path: "/components/radio", component: () => import("./pages/RadioPage.vue") },
    { path: "/components/toggle", component: () => import("./pages/TogglePage.vue") },
    { path: "/components/info-bar", component: () => import("./pages/InfoBarPage.vue") },
    { path: "/components/alert", component: () => import("./pages/AlertPage.vue") },
    { path: "/components/result", component: () => import("./pages/ResultPage.vue") },
    { path: "/components/empty", component: () => import("./pages/EmptyPage.vue") },
    { path: "/components/skeleton", component: () => import("./pages/SkeletonPage.vue") },
    { path: "/components/navigation", component: () => import("./pages/NavigationPage.vue") },
    { path: "/components/breadcrumbs", component: () => import("./pages/BreadcrumbsPage.vue") },
    { path: "/components/sidebar", component: () => import("./pages/SidebarPage.vue") },
    { path: "/components/nav-tabs", component: () => import("./pages/NavTabsPage.vue") },
    { path: "/components/dropdown", component: () => import("./pages/DropdownPage.vue") },
    { path: "/components/modal", component: () => import("./pages/ModalPage.vue") },
    { path: "/components/contextmenu", component: () => import("./pages/ContextmenuPage.vue") },
    { path: "/components/progress", component: () => import("./pages/ProgressPage.vue") },
    { path: "/components/pagination", component: () => import("./pages/PaginationPage.vue") },
    { path: "/components/upload", component: () => import("./pages/UploadPage.vue") },
    { path: "/components/avatar", component: () => import("./pages/AvatarPage.vue") },
    { path: "/components/tag", component: () => import("./pages/TagPage.vue") },
    { path: "/components/table", component: () => import("./pages/TablePage.vue") },
    { path: "/components/message", component: () => import("./pages/MessagePage.vue") },
    { path: "/components/editor", component: () => import("./pages/EditorPage.vue") },
    { path: "/components/compositions", component: () => import("./pages/CompositionsPage.vue") },
  ],
});
